
---

- hosts: chef_servers
  remote_user: root
  vars: 
    - my_mounts:
        - '/'
        - '/boot'

  tasks:

     - name: Check freespace
       shell: df "{{ item }}" | awk '{print $5}' | sed 's/%//'  | tail -1
       register: tmp_freespace
       loop: "{{ my_mounts }}"
       
     - name: Install the latest version of Apache
       yum:
         name: httpd
         state: latest
    
     - name: "Checking Apache Service"
       service: name=httpd state=started

       
     - name: Remove the latest version of Apache
       yum:
         name: httpd
         state: absent
    
...
