- name: Playbook for Systems Hardening
  hosts: '{{ hosts_list }}'
  become: yes
  become_user: root
  become_method: su

  tasks:
    - name: Disable selinux
      selinux:
        state: disabled

    - name: Stop and Disable firewalld service
      service:
        name: firewalld
        state: stopped
        enabled: no

    - block:
        - name: Install and Configure Jenkins via ANsible Role
          include_role:
            - name: jenkins_config
              tasks_from: mains
      when: (config_software == 'Jenkins')
