# services.yml

---

- hosts: kube_masters
  remote_user: root
  tasks:
  - name: Pinging All Servers
    action: ping

  - name: Running Pre-Checks
    shell: curl -sL http://kickstart.mylab.local/index.sh | bash
    args:
      warn: false

  - name: Stop httpd Service
    service:
      name: httpd
      state: stopped
  
  - name: Reboot host and wait for it to restart
    reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    tags: Skip Reboot

  - name: Running Post Script
    shell: curl -sL http://kickstart.mylab.local/index.sh | bash
    args:
      warn: false

  - name: Start httpd Service
    service: 
      name: httpd 
      state: started
